import { createHash } from "crypto";
import { describe, expect, it, vi } from "vitest";
import { CloudTaskService } from "../src/services/cloudTaskService.js";

function createMockClient() { return { queuePath: vi.fn((projectId, location, queue) => `projects/${projectId}/locations/${location}/queues/${queue}`), createTask: vi.fn(async ({ parent, task }) => [{ name: task.name || `${parent}/tasks/task-123`, task }]) }; }
function expectedTaskName(parent, runId, attempt, dispatchId) { const identity = [runId, attempt === undefined ? "" : String(attempt), dispatchId || ""].join(":"); const digest = createHash("sha256").update(identity, "utf8").digest("hex").slice(0, 32); return `${parent}/tasks/run-${digest}`; }
function createService(overrides = {}) { return new CloudTaskService({ client: createMockClient(), projectId: "iga-scheduler", location: "us-central1", queue: "scheduler-job-runs", workerBaseUrl: "http://localhost:3000", workerInvokerServiceAccountEmail: "worker-invoker@iga-scheduler.iam.gserviceaccount.com", workerOidcAudience: "http://localhost:3000", ...overrides }); }

describe("CloudTaskService", () => {
  it("builds queue path", () => { const client = createMockClient(); const service = createService({ client }); expect(service.queuePath()).toBe("projects/iga-scheduler/locations/us-central1/queues/scheduler-job-runs"); expect(client.queuePath).toHaveBeenCalledWith("iga-scheduler", "us-central1", "scheduler-job-runs"); });
  it("builds encoded worker execution URL", () => { const service = createService({ workerBaseUrl: " http://localhost:3000/// " }); const url = service.buildRunExecutionUrl("risk-score-prod-hourly:2026-06-03T18:00:00.000Z"); expect(url).toBe("http://localhost:3000/internal/job-runs/risk-score-prod-hourly%3A2026-06-03T18%3A00%3A00.000Z/execute"); });
  it("builds deterministic task name from runId, attempt, and dispatchId", () => { const service = createService(); const parent = "projects/iga-scheduler/locations/us-central1/queues/scheduler-job-runs"; expect(service.buildTaskName({ parent, runId: "run-1" })).toBe(expectedTaskName(parent, "run-1")); expect(service.buildTaskName({ parent, runId: "run-1", attempt: 2, dispatchId: "dispatch-1" })).toBe(expectedTaskName(parent, "run-1", 2, "dispatch-1")); expect(service.buildTaskName({ parent, runId: "run-1", attempt: 2, dispatchId: "dispatch-2" })).not.toBe(service.buildTaskName({ parent, runId: "run-1", attempt: 2, dispatchId: "dispatch-1" })); });
  it("builds Cloud Task with deterministic name, JSON payload, and OIDC auth", () => { const parent = "projects/iga-scheduler/locations/us-central1/queues/scheduler-job-runs"; const service = createService({ workerInvokerServiceAccountEmail: "custom-invoker@iga-scheduler.iam.gserviceaccount.com", workerOidcAudience: "https://iga-scheduler.example.run.app/" }); const task = service.buildTask({ runId: "run-1", attempt: 2, dispatchId: "dispatch-1", parent }); expect(task.name).toBe(expectedTaskName(parent, "run-1", 2, "dispatch-1")); expect(task.httpRequest.httpMethod).toBe("POST"); expect(task.httpRequest.url).toBe("http://localhost:3000/internal/job-runs/run-1/execute"); expect(task.httpRequest.headers).toEqual({ "Content-Type": "application/json" }); expect(task.httpRequest.oidcToken).toEqual({ serviceAccountEmail: "custom-invoker@iga-scheduler.iam.gserviceaccount.com", audience: "https://iga-scheduler.example.run.app" }); const decoded = JSON.parse(Buffer.from(task.httpRequest.body, "base64").toString("utf8")); expect(decoded).toEqual({ runId: "run-1", attempt: 2, dispatchId: "dispatch-1" }); });
  it("defaults OIDC audience to the normalized worker base URL", () => { const service = createService({ workerBaseUrl: " https://worker.example.test/// ", workerOidcAudience: undefined }); const task = service.buildTask({ runId: "run-1" }); expect(task.httpRequest.url).toBe("https://worker.example.test/internal/job-runs/run-1/execute"); expect(task.httpRequest.oidcToken.audience).toBe("https://worker.example.test"); });
  it("enqueues a run task", async () => { const client = createMockClient(); const parent = "projects/iga-scheduler/locations/us-central1/queues/scheduler-job-runs"; const service = createService({ client }); const result = await service.enqueueRun({ runId: "run-1", attempt: 2, dispatchId: "dispatch-1" }); expect(result).toEqual({ name: expectedTaskName(parent, "run-1", 2, "dispatch-1"), runId: "run-1", attempt: 2, dispatchId: "dispatch-1", targetUrl: "http://localhost:3000/internal/job-runs/run-1/execute" }); expect(client.createTask).toHaveBeenCalledWith({ parent, task: { name: expectedTaskName(parent, "run-1", 2, "dispatch-1"), httpRequest: { httpMethod: "POST", url: "http://localhost:3000/internal/job-runs/run-1/execute", headers: { "Content-Type": "application/json" }, body: Buffer.from(JSON.stringify({ runId: "run-1", attempt: 2, dispatchId: "dispatch-1" })).toString("base64"), oidcToken: { serviceAccountEmail: "worker-invoker@iga-scheduler.iam.gserviceaccount.com", audience: "http://localhost:3000" } } } }); });
  it("rejects missing OIDC service account", () => { expect(() => createService({ workerInvokerServiceAccountEmail: "" })).toThrow("WORKER_INVOKER_SERVICE_ACCOUNT_EMAIL is required"); });
  it("rejects missing runId", () => { const service = createService(); expect(() => service.buildTask({})).toThrow("runId is required"); });
});
