import express from "express";
import request from "supertest";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createInternalSchedulerRouter } from "../src/routes/internalScheduler.js";

function allowAuth(_req, _res, next) { next(); }
function createTestApp(service, options = {}) { const app = express(); app.use(express.json()); const routerOptions = { service }; if (Object.prototype.hasOwnProperty.call(options, "authMiddleware")) routerOptions.authMiddleware = options.authMiddleware; else if (!options.auth && !options.useDefaultAuth) routerOptions.authMiddleware = allowAuth; if (options.auth) routerOptions.auth = options.auth; app.use("/internal/scheduler", createInternalSchedulerRouter(routerOptions)); return app; }
function schedulerRequest(app) { return request(app).post("/internal/scheduler/tick"); }

describe("internal scheduler route", () => {
  afterEach(() => { delete process.env.SCHEDULER_OIDC_AUDIENCE; delete process.env.SCHEDULER_INVOKER_SERVICE_ACCOUNT_EMAIL; delete process.env.WORKER_OIDC_AUDIENCE; delete process.env.WORKER_BASE_URL; delete process.env.WORKER_INVOKER_SERVICE_ACCOUNT_EMAIL; });

  it("runs a scheduler tick with default options", async () => { const service = { tick: vi.fn(async () => ({ status: "ok", checked: 0, createdRuns: 0, duplicates: 0, enqueued: 0, advanced: 0, failed: 0, dryRun: false, enqueue: true })) }; const response = await schedulerRequest(createTestApp(service)).send({}); expect(response.status).toBe(200); expect(response.body).toEqual({ status: "ok", checked: 0, createdRuns: 0, duplicates: 0, enqueued: 0, advanced: 0, failed: 0, dryRun: false, enqueue: true }); expect(service.tick).toHaveBeenCalledWith({ dryRun: false, enqueue: true, batchSize: undefined }); });
  it("passes explicit tick options from the request body", async () => { const service = { tick: vi.fn(async () => ({ status: "ok", checked: 5, createdRuns: 0, duplicates: 0, enqueued: 0, advanced: 0, failed: 0, dryRun: true, enqueue: false })) }; const response = await schedulerRequest(createTestApp(service)).send({ dryRun: true, enqueue: false, batchSize: 5 }); expect(response.status).toBe(200); expect(response.body.checked).toBe(5); expect(service.tick).toHaveBeenCalledWith({ dryRun: true, enqueue: false, batchSize: 5 }); });
  it("rejects requests without an OIDC bearer token", async () => { const service = { tick: vi.fn() }; const app = createTestApp(service, { auth: { expectedAudience: "https://scheduler.example.internal", expectedServiceAccountEmail: "scheduler@example.iam.gserviceaccount.com", verifyToken: vi.fn() } }); const response = await request(app).post("/internal/scheduler/tick").send({}); expect(response.status).toBe(401); expect(response.body).toEqual({ error: "missing bearer token" }); expect(service.tick).not.toHaveBeenCalled(); });
  it("accepts requests with a valid OIDC bearer token", async () => { const service = { tick: vi.fn(async () => ({ status: "ok" })) }; const verifyToken = vi.fn(async () => ({ aud: "https://scheduler.example.internal", email: "scheduler@example.iam.gserviceaccount.com" })); const app = createTestApp(service, { auth: { expectedAudience: "https://scheduler.example.internal", expectedServiceAccountEmail: "scheduler@example.iam.gserviceaccount.com", verifyToken } }); const response = await request(app).post("/internal/scheduler/tick").set("authorization", "Bearer token-1").send({}); expect(response.status).toBe(200); expect(response.body).toEqual({ status: "ok" }); expect(verifyToken).toHaveBeenCalledWith("token-1", { audience: "https://scheduler.example.internal", serviceAccountEmail: "scheduler@example.iam.gserviceaccount.com" }); });
  it("does not fall back to worker OIDC settings", async () => { process.env.WORKER_OIDC_AUDIENCE = "https://worker.example.internal"; process.env.WORKER_BASE_URL = "https://worker.example.internal"; process.env.WORKER_INVOKER_SERVICE_ACCOUNT_EMAIL = "worker@example.iam.gserviceaccount.com"; const service = { tick: vi.fn() }; expect(() => createTestApp(service, { useDefaultAuth: true })).toThrow("expectedAudience is required"); });
  it("uses scheduler-specific OIDC settings by default", async () => { process.env.SCHEDULER_OIDC_AUDIENCE = "https://scheduler.example.internal"; process.env.SCHEDULER_INVOKER_SERVICE_ACCOUNT_EMAIL = "scheduler@example.iam.gserviceaccount.com"; const verifyToken = vi.fn(async () => ({ aud: "https://scheduler.example.internal", email: "scheduler@example.iam.gserviceaccount.com" })); const service = { tick: vi.fn(async () => ({ status: "ok" })) }; const app = createTestApp(service, { useDefaultAuth: true, auth: { expectedAudience: process.env.SCHEDULER_OIDC_AUDIENCE, expectedServiceAccountEmail: process.env.SCHEDULER_INVOKER_SERVICE_ACCOUNT_EMAIL, verifyToken } }); const response = await schedulerRequest(app).set("authorization", "Bearer token-1").send({}); expect(response.status).toBe(200); expect(verifyToken).toHaveBeenCalledWith("token-1", { audience: "https://scheduler.example.internal", serviceAccountEmail: "scheduler@example.iam.gserviceaccount.com" }); });
  it("returns a controlled error when the scheduler tick fails", async () => { const service = { tick: vi.fn(async () => { throw new Error("Elasticsearch unavailable"); }) }; const response = await schedulerRequest(createTestApp(service)).send({}); expect(response.status).toBe(500); expect(response.body).toEqual({ error: "scheduler tick failed", message: "Elasticsearch unavailable" }); });
});
