import express from "express";
import request from "supertest";
import { describe, expect, it, vi } from "vitest";
import { createInternalWorkerRouter } from "../src/routes/internalWorker.js";

function allowAuth(_req, _res, next) { next(); }
function createTestApp(service, options = {}) { const app = express(); app.use(express.json()); app.use("/internal/job-runs", createInternalWorkerRouter({ service, runControlService: options.runControlService, authMiddleware: options.authMiddleware || allowAuth })); return app; }

describe("internal worker route", () => {
  it("rejects anonymous requests when auth middleware denies", async () => { const service = { executeRun: vi.fn() }; const authMiddleware = (_req, res) => res.status(401).json({ error: "missing bearer token" }); const response = await request(createTestApp(service, { authMiddleware })).post("/internal/job-runs/run-1/execute").send({}); expect(response.status).toBe(401); expect(response.body).toEqual({ error: "missing bearer token" }); expect(service.executeRun).not.toHaveBeenCalled(); });

  it("returns completed worker execution responses synchronously", async () => { const service = { executeRun: vi.fn(async ({ runId }) => ({ status: "completed", runId, state: "SUCCEEDED" })) }; const response = await request(createTestApp(service)).post("/internal/job-runs/run-1/execute").send({}); expect(response.status).toBe(200); expect(response.body).toEqual({ status: "completed", runId: "run-1", state: "SUCCEEDED" }); expect(service.executeRun).toHaveBeenCalledWith({ runId: "run-1" }); });

  it("decodes encoded runId", async () => { const service = { executeRun: vi.fn(async ({ runId }) => ({ status: "dispatched", runId, state: "RUNNING" })) }; const encodedRunId = encodeURIComponent("risk-score-prod-hourly:2026-06-03T18:00:00.000Z"); const response = await request(createTestApp(service)).post(`/internal/job-runs/${encodedRunId}/execute`).send({}); expect(response.status).toBe(202); expect(response.body.runId).toBe("risk-score-prod-hourly:2026-06-03T18:00:00.000Z"); expect(service.executeRun).toHaveBeenCalledWith({ runId: "risk-score-prod-hourly:2026-06-03T18:00:00.000Z" }); });

  it("returns service errors instead of acknowledging Cloud Tasks", async () => { const error = new Error("run not found"); error.statusCode = 404; const service = { executeRun: vi.fn(async () => { throw error; }) }; const response = await request(createTestApp(service)).post("/internal/job-runs/missing-run/execute").send({}); expect(response.status).toBe(404); expect(response.body).toEqual({ error: "run not found" }); expect(service.executeRun).toHaveBeenCalledWith({ runId: "missing-run" }); });

  it("routes retry requests to run control service", async () => { const service = { executeRun: vi.fn() }; const runControlService = { retryRun: vi.fn(async () => ({ status: "queued", action: "retry", runId: "run-1", state: "QUEUED", attempt: 2, enqueued: false })) }; const response = await request(createTestApp(service, { runControlService })).post("/internal/job-runs/run-1/retry").send({ enqueue: false }); expect(response.status).toBe(202); expect(response.body).toEqual({ status: "queued", action: "retry", runId: "run-1", state: "QUEUED", attempt: 2, enqueued: false }); expect(runControlService.retryRun).toHaveBeenCalledWith({ runId: "run-1", enqueue: false }); });
  it("routes cancel requests to run control service", async () => { const service = { executeRun: vi.fn() }; const runControlService = { cancelRun: vi.fn(async () => ({ status: "cancelled", action: "cancel", runId: "run-1", state: "CANCELLED" })) }; const response = await request(createTestApp(service, { runControlService })).post("/internal/job-runs/run-1/cancel").send({ reason: "operator requested" }); expect(response.status).toBe(202); expect(response.body).toEqual({ status: "cancelled", action: "cancel", runId: "run-1", state: "CANCELLED" }); expect(runControlService.cancelRun).toHaveBeenCalledWith({ runId: "run-1", reason: "operator requested" }); });
  it("routes re-drive requests to run control service", async () => { const service = { executeRun: vi.fn() }; const runControlService = { redriveRun: vi.fn(async () => ({ status: "queued", action: "redrive", sourceRunId: "run-1", runId: "run-2", state: "QUEUED", attempt: 1, enqueued: true })) }; const response = await request(createTestApp(service, { runControlService })).post("/internal/job-runs/run-1/redrive").send({}); expect(response.status).toBe(202); expect(response.body).toEqual({ status: "queued", action: "redrive", sourceRunId: "run-1", runId: "run-2", state: "QUEUED", attempt: 1, enqueued: true }); expect(runControlService.redriveRun).toHaveBeenCalledWith({ runId: "run-1", enqueue: true }); });
  it("returns run control service transition errors", async () => { const service = { executeRun: vi.fn() }; const error = new Error("run run-1 cannot be retried from state RUNNING"); error.statusCode = 409; const runControlService = { retryRun: vi.fn(async () => { throw error; }) }; const response = await request(createTestApp(service, { runControlService })).post("/internal/job-runs/run-1/retry").send({}); expect(response.status).toBe(409); expect(response.body).toEqual({ error: "run run-1 cannot be retried from state RUNNING" }); });

  it("no longer exposes /complete (SEC-3: removed forgeable completion route)", async () => { const service = { executeRun: vi.fn(), completeRun: vi.fn() }; const response = await request(createTestApp(service)).post("/internal/job-runs/run-1/complete").send({}); expect(response.status).toBe(404); expect(service.completeRun).not.toHaveBeenCalled(); });
});
