import { describe, expect, it, vi } from "vitest";
import { WorkerRunService } from "../src/services/workerRunService.js";

function queuedRun(overrides = {}) { return { runId: "run-1", instanceId: "risk-score-prod-hourly", definitionId: "risk-score", definitionVersion: 1, state: "QUEUED", createdAt: "2026-06-03T18:00:00.000Z", ...overrides }; }
function trustedJobZip(overrides = {}) { return { uri: "gs://iga-scheduler-jobs/approved/risk-score/hash/job.zip", sha256: "hash", generation: "123", approval: { status: "APPROVED", sha256: "hash", generation: "123", approvedBy: "iga" }, scan: { status: "CLEAN", sha256: "hash", scannedBy: "iga" }, ...overrides }; }
function activeDefinition(overrides = {}) { return { definitionId: "risk-score", version: 1, state: "ACTIVE", enabled: true, runtime: "javascript", runtimeVersion: "nodejs22", wrapperVersion: "1.0.0", entrypoint: "index.js", timeoutSeconds: 1800, jobZip: trustedJobZip(), ...overrides }; }
function createMockEsClient({ run = queuedRun(), definition = activeDefinition(), getImpl, createImpl, updateImpl } = {}) { return { get: vi.fn(getImpl || (async ({ index }) => index === "scheduler_definitions_v1" ? { _source: definition } : { _source: run })), update: vi.fn(updateImpl || (async () => ({ result: "updated" }))), create: vi.fn(createImpl || (async () => ({ result: "created" }))) }; }
function createRuntimeExecutor(result = { status: "completed", output: { ok: true } }) { return { execute: vi.fn(async () => result) }; }
function createParameterResolver(resolved = {}) { return { resolveParameters: vi.fn(async () => resolved) }; }
function stubArtifactVerification(service) { vi.spyOn(service, "verifyApprovedArtifact").mockResolvedValue({ sha256: "hash", generation: "123", fileCount: 2, uncompressedBytes: 53, buffer: Buffer.from("zip-bytes") }); }
function fixedClock(...values) { let index = 0; return () => new Date(values[Math.min(index++, values.length - 1)]); }
function auditEvents(esClient) { return esClient.create.mock.calls.map(([call]) => call.document).filter((event) => event?.eventType); }
function auditEventTypes(esClient) { return auditEvents(esClient).map((event) => event.eventType); }

describe("WorkerRunService", () => {
  it("marks a queued run running and then succeeded", async () => { const esClient = createMockEsClient({ run: queuedRun({ params: { window: { type: "string", value: "PT1H" }, apiKey: { type: "sensitive", secretRef: "iga-api-key" } } }) }); const runtimeExecutor = createRuntimeExecutor({ status: "completed", runId: "run-1", runtime: "javascript", runtimeVersion: "nodejs22", entrypoint: "index.js", exitCode: 0, timedOut: false, stdout: "ok", stdoutTruncated: false, output: { ok: true }, ignoredField: "do-not-persist" }); const parameterResolver = createParameterResolver({ window: "PT1H", apiKey: "resolved-secret" }); const service = new WorkerRunService({ esClient, storage: {}, runtimeExecutor, parameterResolver, now: fixedClock("2026-06-03T18:01:00.000Z", "2026-06-03T18:01:05.000Z") }); stubArtifactVerification(service); const result = await service.executeRun({ runId: "run-1" }); expect(result.status).toBe("completed"); expect(result.state).toBe("SUCCEEDED"); expect(result.result).toEqual({ status: "completed", runId: "run-1", runtime: "javascript", runtimeVersion: "nodejs22", entrypoint: "index.js", exitCode: 0, timedOut: false, stdout: "ok", stdoutTruncated: false, output: { ok: true } }); expect(result.result.ignoredField).toBeUndefined(); expect(parameterResolver.resolveParameters).toHaveBeenCalledWith({ window: { type: "string", value: "PT1H" }, apiKey: { type: "sensitive", secretRef: "iga-api-key" } }); expect(runtimeExecutor.execute).toHaveBeenCalledWith(expect.objectContaining({ runId: "run-1", artifactBuffer: Buffer.from("zip-bytes"), context: expect.objectContaining({ runId: "run-1", definition: expect.objectContaining({ definitionId: "risk-score", version: 1, runtime: "javascript", entrypoint: "index.js" }), instance: { instanceId: "risk-score-prod-hourly" }, params: { window: "PT1H", apiKey: "resolved-secret" }, igaBridge: { capabilities: ["riskScores.recompute", "health.check"] } }) })); expect(runtimeExecutor.execute.mock.calls[0][0].context.params.apiKey).not.toEqual({ type: "sensitive", secretRef: "iga-api-key" }); expect(esClient.update).toHaveBeenCalledTimes(2); const claimUpdate = esClient.update.mock.calls[0][0]; expect(claimUpdate.if_seq_no).toBeUndefined(); expect(claimUpdate.if_primary_term).toBeUndefined(); expect(claimUpdate.script.source).toContain("ctx._source.state == 'QUEUED'"); const successUpdate = esClient.update.mock.calls[1][0]; expect(successUpdate.script.source).toContain("ctx._source.state == 'RUNNING'"); expect(successUpdate.script.params).toEqual(expect.objectContaining({ endedAt: "2026-06-03T18:01:05.000Z", result: result.result, status: { phase: "succeeded", message: "Run completed successfully" } })); expect(auditEventTypes(esClient)).toEqual(["worker.run.received", "worker.claim.attempted", "worker.claim.succeeded", "WORKER_RUN_STARTED", "worker.metadata.loaded", "worker.artifact.verified", "worker.execution.started", "worker.execution.succeeded"]); });

  it("requires a launcher when constructed in isolated mode", () => { expect(() => new WorkerRunService({ esClient: createMockEsClient(), storage: {}, executionMode: "isolated" })).toThrow("isolatedRuntimeLauncher is required when executionMode is isolated"); });

  it("dispatches isolated runs without resolving sensitive parameters", async () => { const run = queuedRun({ params: { apiKey: { type: "sensitive", secretRef: "iga-api-key" }, window: { type: "string", value: "PT1H" } } }); const esClient = createMockEsClient({ run }); const parameterResolver = createParameterResolver({ apiKey: "resolved-secret", window: "PT1H" }); const isolatedRuntimeLauncher = { launchExecution: vi.fn(async () => ({ backend: "cloud-run-job", executionId: "exec-1" })) }; const service = new WorkerRunService({ esClient, storage: {}, executionMode: "isolated", isolatedRuntimeLauncher, parameterResolver, now: fixedClock("2026-06-03T18:01:00.000Z") }); const result = await service.executeRun({ runId: "run-1" }); expect(result.status).toBe("dispatched"); expect(parameterResolver.resolveParameters).not.toHaveBeenCalled(); const launchRequest = isolatedRuntimeLauncher.launchExecution.mock.calls[0][0]; expect(launchRequest.context.params).toEqual(run.params); expect(JSON.stringify(launchRequest.context)).not.toContain("resolved-secret"); expect(launchRequest.context.params.apiKey).toEqual({ type: "sensitive", secretRef: "iga-api-key" }); });

  it("skips duplicate delivery when claim script noops", async () => { const getResponses = [{ _source: queuedRun() }, { _source: queuedRun({ state: "RUNNING" }) }]; const esClient = createMockEsClient({ getImpl: async () => getResponses.shift(), updateImpl: async () => ({ result: "noop" }) }); const runtimeExecutor = createRuntimeExecutor(); const service = new WorkerRunService({ esClient, storage: {}, runtimeExecutor, parameterResolver: createParameterResolver(), now: fixedClock("2026-06-03T18:01:00.000Z") }); const result = await service.executeRun({ runId: "run-1" }); expect(result.status).toBe("skipped"); expect(result.state).toBe("RUNNING"); expect(runtimeExecutor.execute).not.toHaveBeenCalled(); expect(esClient.update.mock.calls[0][0].script.source).toContain("ctx._source.state == 'QUEUED'"); });
  it("fails non-retryably when artifact approval is missing", async () => { const esClient = createMockEsClient({ definition: activeDefinition({ jobZip: trustedJobZip({ approval: undefined }) }) }); const runtimeExecutor = createRuntimeExecutor(); const service = new WorkerRunService({ esClient, storage: {}, runtimeExecutor, parameterResolver: createParameterResolver(), now: fixedClock("2026-06-03T18:01:00.000Z", "2026-06-03T18:01:05.000Z") }); await expect(service.executeRun({ runId: "run-1" })).rejects.toMatchObject({ code: "ARTIFACT_NOT_APPROVED" }); expect(runtimeExecutor.execute).not.toHaveBeenCalled(); const failureUpdate = esClient.update.mock.calls[1][0]; expect(failureUpdate.script.source).toContain("ctx._source.state == 'RUNNING'"); expect(failureUpdate.script.params.error).toEqual(expect.objectContaining({ code: "ARTIFACT_NOT_APPROVED", retry: expect.objectContaining({ retryable: false }) })); });
  it("returns not found for missing run", async () => { const notFound = new Error("not found"); notFound.meta = { statusCode: 404 }; const esClient = createMockEsClient({ getImpl: async () => { throw notFound; } }); const service = new WorkerRunService({ esClient, storage: {}, parameterResolver: createParameterResolver() }); await expect(service.executeRun({ runId: "missing-run" })).rejects.toMatchObject({ message: "run not found", statusCode: 404 }); expect(esClient.update).not.toHaveBeenCalled(); expect(auditEventTypes(esClient)).toEqual(["worker.run.received", "worker.execution.failed"]); });
  it("is idempotent for non-queued runs", async () => { const esClient = createMockEsClient({ run: queuedRun({ state: "SUCCEEDED" }) }); const runtimeExecutor = createRuntimeExecutor(); const service = new WorkerRunService({ esClient, storage: {}, runtimeExecutor, parameterResolver: createParameterResolver() }); const result = await service.executeRun({ runId: "run-1" }); expect(result).toEqual({ status: "skipped", runId: "run-1", state: "SUCCEEDED", message: "Run is SUCCEEDED; worker execution was not started" }); expect(runtimeExecutor.execute).not.toHaveBeenCalled(); expect(esClient.update).not.toHaveBeenCalled(); expect(auditEventTypes(esClient)).toEqual(["worker.run.received", "worker.claim.skipped"]); });
  it("records claim skipped when the queued run is already claimed", async () => { const getResponses = [{ _source: queuedRun() }, { _source: queuedRun({ state: "RUNNING" }) }]; const esClient = createMockEsClient({ getImpl: async () => getResponses.shift() }); esClient.update = vi.fn(async () => ({ result: "noop" })); const runtimeExecutor = createRuntimeExecutor(); const service = new WorkerRunService({ esClient, storage: {}, runtimeExecutor, parameterResolver: createParameterResolver(), now: fixedClock("2026-06-03T18:01:00.000Z") }); const result = await service.executeRun({ runId: "run-1" }); expect(result.status).toBe("skipped"); expect(result.state).toBe("RUNNING"); expect(runtimeExecutor.execute).not.toHaveBeenCalled(); expect(esClient.update).toHaveBeenCalledTimes(1); expect(auditEventTypes(esClient)).toEqual(["worker.run.received", "worker.claim.attempted", "worker.claim.skipped"]); });
  it("marks a run failed when runtime executor throws", async () => { const esClient = createMockEsClient(); const runtimeError = new Error("runtime failed"); runtimeError.code = "RUNTIME_PROCESS_EXITED_NON_ZERO"; runtimeError.execution = { status: "failed", exitCode: 7, stderr: "boom", ignoredFailureField: "do-not-persist" }; const runtimeExecutor = { execute: vi.fn(async () => { throw runtimeError; }) }; const service = new WorkerRunService({ esClient, storage: {}, runtimeExecutor, parameterResolver: createParameterResolver(), now: fixedClock("2026-06-03T18:01:00.000Z", "2026-06-03T18:01:05.000Z") }); stubArtifactVerification(service); await expect(service.executeRun({ runId: "run-1" })).rejects.toThrow("runtime failed"); expect(esClient.update).toHaveBeenCalledTimes(2); const failureUpdate = esClient.update.mock.calls[1][0]; expect(failureUpdate.script.source).toContain("ctx._source.state == 'RUNNING'"); expect(failureUpdate.script.params).toEqual(expect.objectContaining({ endedAt: "2026-06-03T18:01:05.000Z", status: { phase: "failed", message: "Run failed in worker runtime executor" }, error: expect.objectContaining({ code: "RUNTIME_PROCESS_EXITED_NON_ZERO", message: "runtime failed", retry: { retryable: true, classification: "RETRYABLE", reason: "retryable_code:RUNTIME_PROCESS_EXITED_NON_ZERO" } }) })); expect(failureUpdate.script.params.error.execution).toEqual(expect.objectContaining({ status: "failed", exitCode: 7, stderr: "boom" })); expect(failureUpdate.script.params.error.execution.ignoredFailureField).toBeUndefined(); const failedEvent = auditEvents(esClient).find((event) => event.eventType === "worker.execution.failed"); expect(failedEvent).toEqual(expect.objectContaining({ eventType: "worker.execution.failed", runId: "run-1", retryable: true, retryClassification: "RETRYABLE", retryReason: "retryable_code:RUNTIME_PROCESS_EXITED_NON_ZERO", errorCode: "RUNTIME_PROCESS_EXITED_NON_ZERO", errorMessage: "runtime failed" })); });
  it("does not fail the worker run when ES audit recording fails", async () => { const esClient = createMockEsClient({ createImpl: async () => { throw new Error("audit unavailable"); } }); const logger = { warn: vi.fn() }; const runtimeExecutor = createRuntimeExecutor({ status: "completed", runId: "run-1" }); const service = new WorkerRunService({ esClient, storage: {}, logger, runtimeExecutor, parameterResolver: createParameterResolver(), now: fixedClock("2026-06-03T18:01:00.000Z", "2026-06-03T18:01:05.000Z") }); stubArtifactVerification(service); const result = await service.executeRun({ runId: "run-1" }); expect(result.status).toBe("completed"); expect(result.state).toBe("SUCCEEDED"); expect(runtimeExecutor.execute).toHaveBeenCalled(); expect(esClient.create).toHaveBeenCalled(); expect(logger.warn).toHaveBeenCalledWith("worker audit emit failed", expect.objectContaining({ error: "audit unavailable" })); });
});
